server:
  port: 8888

spring:
  application:
    name: hm-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
  security:
    user:
      name: config-admin
      password: ${CONFIG_SERVER_PASSWORD:config-secret-2026}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always

logging:
  level:
    org.springframework.cloud.config: INFO
