server:
  port: 8101
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/appointment_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  kafka:
    consumer:
      group-id: appointment-service-group
