server:
  port: 8105
spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/notification_db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  kafka:
    consumer:
      group-id: notification-service-group
